version: "3.8"

services:
  node-service:
    build: .
    container_name: node-service
    expose:
      - "3000"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    extra_hosts:
      - "api.binance.com:13.225.103.45"
      - "api1.binance.com:13.225.103.45"
      - "api2.binance.com:13.225.103.45"
      - "api3.binance.com:13.225.103.45"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - node-network
    environment:
      - NODE_ENV=development

networks:
  node-network:
    name: node-network
    driver: bridge
