# version: "3.8"
name: TradingAnalyzer
services:
  trading-analyzer:
    build: .
    container_name: trading-analyzer
    expose:
      - "3000"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    extra_hosts:
      - "api.binance.com:13.225.103.45"
      - "api1.binance.com:13.225.103.45"
      - "api2.binance.com:13.225.103.45"
      - "api3.binance.com:13.225.103.45"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - trading-network
    environment:
      - NODE_ENV=development

networks:
  trading-network:
    name: trading-network
    driver: bridge
